### ISSUE TITLE
GF Repeater Add-On + GF Entries in Excel

### ISSUE THREAD

**Issue by mircobabini** [doekenorg/gf-entries-in-excel#28]
Hey Doeke! Hope you're doing well.

I'm exporting a form containing a repeater field in Excel, the code is not really generic because into the repeater field I make some decisions, based on the input of the user. It's not just some data to explode into an excel.

By the way I'd love to discuss it with you, maybe you are interested into making it generic and integrated.

Actually, a repeater field is automatically rendered like this (not so useful into an excel):
`Brand: A, Percentuale: 20, Brand: B, Percentuale: 10, Brand: Altro, Percentuale: 30, Altro brand: Nome del brand`

Instead, I need something more excel-style.
This is the current (working) code: https://gist.github.com/mircobabini/dd2d47f7cc928f869d84ab1b32296a4b

As you can see I'm instancing the class on the form + (repeater) field.
Then, I'm working on rows and columns in order to transform this: https://snag.gy/mopGbS.jpg (or this: https://snag.gy/XDx8FU.jpg) to that: https://snag.gy/cCpo2v.jpg 

Please note that I'm NOT parsing the serialization of the repeater; the script uses the original field data from get_field( ... )->getValue().

What do you think? :)

**Comment by mircobabini** [comment]
Uh, just a note: of course I disabled the repeater-fields end the repeater-closer: https://snag.gy/Z6dqF9.jpg

**Comment by mircobabini** [comment]
Hey, had to update the code. The worst thing I've done is the way I guess the index of the excel column where the repeater will appear. I loop on the form fields looking for the field_id, skipping the sections and the file_uploads. Pretty sure there's a better way to identity the excel column (not based on the name, that might be empty); maybe you should give more info when you pass the $colums to the gfexcel_output_columns filter :)

**Comment by doekenorg** [comment]
@mircobabini Gonna reply with more details, but with regards to your latest comment: see #26 😄 Those objects are going to be the way to go. Gonna check the rest of the implementation later today. But I think off the bat, you probably going to want to use a specific transformer, instead of using these hooks. 

You'll get more details. Promise 😉

**Comment by mircobabini** [comment]
Yes, just noticed the transformers and more specifically the "FileUploadField::showFileUploadsAsColumn" so yeah, I'm doing it the reaaaally wrong way. :)

**Comment by doekenorg** [comment]
As a bonus, you don't need those value objects, they get in later on. So you can just make a custom transformer, and add it via the hook. Checkout `Transformer.php`. You have all the details of the field available in that class. 💪

**Comment by doekenorg** [comment]
Hi @mircobabini, 

Could you provide me with an example as to how you would like the output to be? I'm kind of struggling, because I don't want to add extra rows. 

What are your thoughts on this?

**Comment by mircobabini** [comment]
Well, my example is a bit complicated. Maybe something that needs some code.

But I think there are two interesting particular cases. I prepared an example: https://docs.google.com/spreadsheets/d/1M3WZkzEQM2bAO470cFNsVwqUv0QGFV6UKX9ryxqgKe0/edit?usp=sharing

Feel free to edit it. Just a few notes:
- First example, the results (on a SINGLE ENTRY) is a table with N rows, N = the number of times the repeater + is used.
- Second example, the results (on a SINGLE ENTRY) is a table where columns are growing every time the repeater + is used, because a field in the repeater is declared as "key", while the other is declared as "value".

Well, the second case is more similar to what I developed above. But, you know... more fields, more struggle. Don't know, maybe it's simply overcomplicated.

**Comment by doekenorg** [comment]
Right, well I had a similar question in [the support forum](https://wordpress.org/support/topic/two-questions-54/) and I've elaborated a bit on that answer. 

I really like the fact that every row is an entry. It's clear, and concise. But I also understand that some fields just don't work like that. My solution was to group al the fields, and merge them with a new line. This works, as long as the use doesn't use CSV 😛 or uses new lines within the field. I could also use a pipe-symbol `|` for example, but that would ruin the readability. 

Fact is, in the current code base, example one just isn't an option. This is because the rows are set before the fields are rendered. So when we start working with the fields, we can only manipulate the row we are in. 

Example two is 'maybe'. We can manipulate the current row, and add columns. But thats where the fun ends. We cant manipulate any of the OTHER rows. And we need that, because every other row should have the same amount of columns to make the other data get in the correct column. 

Although I'm leaning towards option one, I'm really hoping we can figure out a third option that satisfies this field, and also the list field 😄. I'm gonna sleep on it for now.

**Comment by mircobabini** [comment]
An addition on the second case. Well, it’s not true that we cannot add the needed columns on all the rows. This is where my code comes in.

I solved the issue through two loops on rows. The first one just reads and creates the list of columns to add.

The second loop adds all the columns to every row, using a default value when no value is provided for the specific column on the specific row.

Suboptimal? Maybe. But it works. And it’s also the most useful way to have data filled into an excel. You can elaborate the data with less effort than having to split a string by a separator.

**Comment by doekenorg** [comment]
I still feel like option two is not really user-friendly. It will make short entries really long rows with empty values if there is only one entry that has a lot of repeating fields. And although that may work for you, I'm not sure that this is a generic solution for everybody. I might consider both as an option to select.

I have some ideas to make option one a workable option. Making it possible for a transformer to add more rows. Still feel like a transformer should only know about it's own entry, but maybe it can be stretched over more rows. 

And using keys as labels only makes sense for me if every entry is the same, or with only one entry per file.

**Comment by doekenorg** [comment]
The next release will split repeaters into multiple fields, but only once. Every row for that field is combined with a (overwritable) value of `\n---\n` making it easier to see what values belong together. 

Whenever I'm ready to add multiple rows from within the field transformer, these will be extracted to their own rows (when the user wants it so). 

Just wanted to let you know this issue is still very much on my radar.

**Comment by doekenorg** [comment]
@mircobabini I've (finally) fixed this. The next release (1.8.0) will have a hook that allows you to replace the combining of columns to rows.

I'm currently [building a premium add-on](http://subscribe.gfexcel.com/pro-add-on) that will have this option. So this will not be in the current plugin. However, I'm willing to give you the premium multi-row-combiner 😄 . 

If you are (still) interested in this, please drop me an e-mail. I'll send you the necessary file, and we can finally close this issue 😄

**Comment by mircobabini** [comment]
That's great! Yep, just subscribed to the premium add-on waiting list and of course I want to be a beta tester! I'm in :) Thank you!

**Comment by mircobabini** [comment]
Hey, you received my email? :)

**Comment by doekenorg** [comment]
Yes sorry. As soon as 1.8.0 is out you'll receive the file. Waiting on
someone to deliver some translations. But holidays.

Soon™

Op do 30 jul. 2020 14:56 schreef Mirco Babini <notifications@github.com>:

**Comment by doekenorg** [comment]
Version released. File heading your way. So that means I can FINALLY close this issue. Enjoy!
